-- Box1 데이터 가져오기 (자동 생성, 총 130건)
insert into chemicals (category, storage_position, company, cas_no, catalogue_no, compound_name, purity_conc, container_size, container_type, phase, quantity_total, opened_date) values
('box1', 'A1', 'Sigma-Aldrich', NULL, NULL, 'sodium triethylborohydride solution (1.0M in toluene)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'A1', 'Sigma-Aldrich', NULL, NULL, 'super-hydride solution(1.0M lithium triethylborohydride in THF)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'A1', 'Sigma-Aldrich', NULL, NULL, 'potassium triethylborohydride solution (1.0M in THf)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'A1', 'thermo scientific', NULL, NULL, 'sodium triacetoxyborohydride', '0.97', '25 g', NULL, NULL, 1, NULL),
('box1', 'A1', 'TCI', NULL, NULL, 'lithium aluminum hydride(powder)', NULL, '25g', NULL, NULL, 1, NULL),
('box1', 'A1', 'Tci', NULL, NULL, 'lithium trifuloromthanesulfonate', '0.98', '25g', NULL, NULL, 1, NULL),
('box1', 'A1', 'thermo scientific', NULL, NULL, 'potassium hexafluorophosphate', '0.99', '50 g', NULL, NULL, 1, NULL),
('box1', 'A1', '대정', NULL, NULL, 'potassium cyanide', '0.98', NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'sodium tertiarybutoxide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'sodium hexafluorophosphate', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'manganese(II) dichloride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'Zinc(II) dichloride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'iron(II) dicholoride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'cobalt(II) dibromide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'copper(I) bromide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'vanadium(II) dichloride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', NULL, NULL, NULL, 'iron(II) dibromide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A1', 'thermo scientific', NULL, NULL, 'fomblin YR 1800', NULL, '5 g', NULL, NULL, 1, NULL),
('box1', 'A1', 'Alfa', NULL, NULL, 'pentafluoropyridine', NULL, '5 g', NULL, NULL, 1, NULL),
('box1', 'A1', 'Alfa', NULL, NULL, '2-fluoropyridine', NULL, '10 g', NULL, NULL, 1, NULL),
('box1', 'A2', 'thermo scientific', NULL, NULL, 'sodium triacetoxyborohydride', '0.97', '25 g', NULL, NULL, 1, NULL),
('box1', 'A2', 'thermo scientific', NULL, NULL, 'formic acid', '0.99', '25 ml', NULL, NULL, 1, NULL),
('box1', 'A2', 'thermo scientific', NULL, NULL, 'formic acid', '0.99', '25 ml', NULL, NULL, 1, NULL),
('box1', 'A2', 'sigma-aldrich', NULL, NULL, 'p-Cresol', '0.99', '5 g', NULL, NULL, 1, NULL),
('box1', 'A2', 'TCI', NULL, NULL, 'tris(pentafluorophenyl)borane', '0.97', '1 g', NULL, NULL, 1, NULL),
('box1', 'A2', 'sigma-aldrich', NULL, NULL, 'phenylboronic acid pinacol ester', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'A2', 'TCI', NULL, NULL, 'boron trifluoride-ethyl ether complex', '0.98', '100 ml', NULL, NULL, 1, NULL),
('box1', 'A2', 'Deutero', NULL, NULL, 'DMSO-d6', '0.998', '100 mL', NULL, NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'copper(I) chloride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'copper(I) chloride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', 'sigma-aldrich', NULL, NULL, '2,4,6-tri-tertiarybutylphenol', '0.98', NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', 'sigma-aldrich', NULL, NULL, '2,4,6-tri-tertiarybutylphenol', '0.98', NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'benzophenone', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'naphthalene', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'naphthalene', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'naphthalene', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'triphenylphosphine', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', 'alpha aesar', NULL, NULL, '2,2''-bipyridine', '0.99', NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'B2pin2', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'sodium hydride', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'sodium nitrite', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'copper(II) dibromide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, 'potassium(I) bromide', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', 'sigma-aldrich', NULL, NULL, '2-hydroxy pyridine', '0.97', NULL, 'vial', NULL, 1, NULL),
('box1', 'A2', NULL, NULL, NULL, '2,4-di-tertiarybutylphenol', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'tris(4-brom+B39:I54ophenyl)amine', '0.98', '10 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'copper(I) chloride', '0.99', '25 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'TCI', NULL, NULL, '18-crown-6-ether', '0.98', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '1,4-diiodobenzene', '0.99', '50 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'phenylboronic acid', '0.95', '10 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '12-crown-4', '0.98', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '12-crown-4', '0.98', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'pyrazine', '0.99', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'sodium bis(trimethylsilyl)amide solution (1.0M in THF)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'Thiophenol', '0.99', '10 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '4-(trifluoromethyl)phenol', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'silver nitrate', '0.99', '25 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, 'trimethylamine N-oxide', '?', '1 g', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '(R)-BINAP', NULL, '100 mg', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '(R)-BINAP', NULL, '100 mg', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '(R)-BINAP', NULL, '100 mg', NULL, NULL, 1, NULL),
('box1', 'A3', 'sigma-aldrich', NULL, NULL, '4-methoxy phenol', '0.99', '5 g', NULL, NULL, 1, NULL),
('box1', 'A3', NULL, NULL, NULL, 'Al powder', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A3', NULL, NULL, NULL, 'TBA nitrite', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'A3', NULL, NULL, NULL, 'TBA nitrate', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'bismuth(iII) chloride', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'silver(I) oxide', '0.99', '10 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'chlorotris(triphynylphosphine)Ru(II)acetate', '0.97', '2 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'alpha aesar', NULL, NULL, 'bis(1,5-cyclooctadiene)iridium(I)tetrafluoroborate', NULL, '1 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'antimony(III)iodide', '0.98', '10 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'tetrakis(acetonitrile)copper(I)tetrafluoroborate', '0.97', '1 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'tetrakis(acetonitrile)copper(I)hexafluorophosphate', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'dichloro(p-cymene)ruthenium(II) dimer', NULL, '1 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'chloro(1,3-bis(2,4,6-trimethylphenyl)-imidazol-2-ylidene)copper(I)', '0.95', '250 mg', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'tris(dibenzyllideneacetone)dipalladium(0)', '0.97', '500 mg', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'tris(dibenzyllideneacetone)dipalladium(0)', '0.97', '500 mg', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'tetrakis(acetonitrile)copper(I)tetrafluoroborate', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', NULL, NULL, NULL, 'platinum(II) chloride', '0.999', '1 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'alpha aesar', NULL, NULL, 'Ni(II) iodide', '0.995', '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'copper(II) trifluoromethanesulfonate', '0.98', '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'sigma-aldrich', NULL, NULL, 'carbonylchlorohydridotris(triphenylphosphine)ruthenium(II)', NULL, '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', 'thermoscientific', NULL, NULL, 'dichlorotris(triphenylphosphine)Ruthenium(II)', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'B1', NULL, NULL, NULL, 'Pd2dba3', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'B2', 'TCI', NULL, NULL, '2,2''-bipyridine-6,6''-diol', '0.98', '1 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'TCI', NULL, NULL, '1-methylimidazole', '0.99', '25 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'sigma-aldrich', NULL, NULL, 'triethylamine', '0.995', '100 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'fluorobenzene', '0.99', '250 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'sigma-aldrich', NULL, NULL, 'pyrrolidine', '0.995', '100 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'N,N''-dimethylethylene diamine', '0.95', '25 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'TMEDA', '0.995', '100 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'potassium tert-butoxide', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'sigma-aldrich', NULL, NULL, 'sodium tertraphenylborate', '0.995', '25 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'Lithium tert-butoxide', '0.999', '50 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'TCI', NULL, NULL, 'bis(2-chloroethyl)amine hydrochloride', '0.99', '100 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'Sigma-Aldrich', NULL, NULL, 'N,N-diisopropylethylamine', '0.995', '100 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'Sigma-Aldrich', NULL, NULL, '1,4-dioxane', '0.998', '100 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'TCI', NULL, NULL, 'ethylenediamine anhydrous', '0.98', '25 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, '1,8-bis(dimethylamino)naphthalene', '0.99', '10 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'Sigma-Aldrich', NULL, NULL, 'DBU', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'B2', 'TCI', NULL, NULL, '1,3-diaminopropane', '0.98', '25 mL', NULL, NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, '18-crown-6', '0.99', NULL, 'vial', NULL, 1, NULL),
('box1', 'B2', NULL, NULL, NULL, 'bipyridine', NULL, NULL, 'vial', NULL, 1, NULL),
('box1', 'B2', 'thermoscientific', NULL, NULL, 'methanol', '0.999', '1 L', NULL, NULL, 1, NULL),
('box1', 'B2', 'sigma-aldrich', NULL, NULL, '2-methyltetrahydrofuran', '0.99', '1 L', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'tButyl isocyanide', NULL, '?', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'Ni(COD)2', NULL, '2 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'Ni(COD)2', NULL, '2 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'Ni(COD)2', NULL, '2 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'Ni(COD)2', NULL, '2 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'thermoscientific', NULL, NULL, 'tButyl isocyanide', '0.97', '5 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'chloro diisopropylphsophine', '0.96', '5 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'chloro diisopropylphsophine', '0.96', '5 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'chloro diisopropylphsophine', '0.96', '5 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'chloro(1,3-bis(2,4,6-trimethylphenyl)imidazol-2-ylidene)copper(I)', '0.95', '250 mg', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'benzyl amine', '0.99', '5 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'acros', NULL, NULL, 'benzyl isocyanide', '0.98', '1 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'sigma-aldrich', NULL, NULL, 'tetrakis(triphenylphosphine)platinum(0)', '0.97', '1 g', NULL, NULL, 1, NULL),
('box1', 'freezer', 'deutero', NULL, NULL, 'THF-d8', '0.995', '25 mL', NULL, NULL, 1, NULL),
('box1', 'etc', 'TCI', NULL, NULL, 'tetraphenylphosphonium tetraphenyl borate', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'etc', 'TCI', NULL, NULL, 'tetraphenylphosphonium bromide', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'etc', 'TCI', NULL, NULL, 'silver(I) oxide', '0.99', '5 g', NULL, NULL, 1, NULL),
('box1', 'etc', 'TCI', NULL, NULL, 'p,p''-ditolylamine', '0.98', '25 g', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'methylmagnesium chloride solution (3.0M in THF)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'hydrogen chloride solution (1.0M in diethyl ether)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'methyl lithium solution(1.6M in diethyl ether)', NULL, '25 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'iodomethane solution(2.0M in tbutyl bethyl ether)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, '3-methyl-2-oxazolidinone', '0.995', '25 g', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'n-Butyllithium solution(1.6M in hexane)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'n-Butyllithium solution(1.6M in hexane)', NULL, '100 mL', NULL, NULL, 1, NULL),
('box1', 'drop freezer', 'sigma-aldrich', NULL, NULL, 'tetrakis(dimethylsulfoxide) dichloro Ruthenium(II)', '0.96', '5 g', NULL, NULL, 1, NULL);
