-- Box2(Co Box)/Box3(Fe Box) 데이터 가져오기 (자동 생성, 총 342건)
insert into chemicals (category, storage_position, company, cas_no, catalogue_no, compound_name, purity_conc, container_size, container_type, phase, quantity_total, opened_date) values
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '1-Bromoadamantane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '3-Phenylbenzylbromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '9-Fluorenone', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Benzaldehyde Oxime', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '4-tert-butylbenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Tetramethylammonium nitrate', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '3-Nitrobenzyl bromide', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Alfa aesar', NULL, NULL, 'tert-Butyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-(trifluoromethoxyl)benzylbromide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '9-fluorenone oxime', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '9-fluorenone oxime', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '9,10-dihydro-9,9-dimethyl acridine', NULL, '1G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Sodium bis(trimethylsilyl)amide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '1,10-phenanthroline', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, 'Cyclohexyl p-Toluenesulfonate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '4-Fluoropyridine Hydrochloride', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '4-Phenylbenzoyl Chloride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '1,1,3,3,-Ttramethyldisiloxane', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, 'm-Toluoyl Chloride', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, 'p-Toluoyl Chloride', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Dimethylphenylsilane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Thermo', NULL, NULL, '4-Chlorobenzoyl chloride', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, '2-Bromomethylpyridine hydrobromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, '1-Bromobenzocyclobutene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Iodine', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, '1-Boc-4-bromopiperidine', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Triethylsilane', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Tetrabutylammonium nitrate', NULL, '2 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Poly(methylhydrosiloxane)', NULL, '50 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Eurisotop', NULL, NULL, 'Tetrahydrofuran-D8', NULL, '10 ml', NULL, NULL, 1, NULL),
('box3', 'B2', 'Thermo', NULL, NULL, '4-Bromobenzoyl chloride', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Thermo', NULL, NULL, '2-Napthoyl chloride', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Sodium hydride', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Potassium tert-butoxide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'TCI', NULL, NULL, 'Trimethylamine Borane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Thermo', NULL, NULL, 'Zinc bromide anhydrous', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Thermo', NULL, NULL, 'Graphite powder', NULL, '28 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Lithium hydride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Thermo', NULL, NULL, 'Lithium nitrate, anhydrous', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Potassium carbonate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Cessium carbonate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Sodium nitrate', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Fe(0) pentacarbonyl', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'A1', 'Sigma Aldrich', NULL, NULL, 'Potassium bicarbonate', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A1', 'vial', NULL, NULL, 'LiAlH4', NULL, '<10 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Thermo', NULL, NULL, 'Copper(2) bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Silver nitrate', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Nitromethane', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Nickel(2) bromide ethylene glyco dimethyl ether complex', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'TCI', NULL, NULL, 'Silver Bis(trifluoromethane-sulfonyl)imide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Ruthenium(3) chloride', NULL, '2 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Acros', NULL, NULL, 'Nickel(2) bromide', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, '(1,3-Bis(diphenylphosphino)propane)dichloronickel(2)', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Acros', NULL, NULL, 'Nickel(2) bromide', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Nickel(2) trifluoromethnaesulfonate', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Potassium nitrate', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Silver nitrite', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Sodium iodide', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Acros', NULL, NULL, 'Calcium sulfate', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A2', 'Sigma Aldrich', NULL, NULL, 'Cobalt(2) bromide', NULL, '50 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '2-Bromo-2-phenylacetophenone', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, 'Chlorotrimethylsilane', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, 'Bromocyclopentane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, 'Tetraphenylphosphonium bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, 'Dimethylammonium dimethylcarbamate', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '3-(trifluoromethoxy)benzyl bromide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '2-(Bromomethyl)quinoline', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '6(5H)-Phenanthridinone', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, '1-Bromooctane', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, 'Chlorodiphenylphosphine', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '2-Bromo-2-methylpropane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Alfa aesar', NULL, NULL, 'pentafluoropyridine', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Thermo', NULL, NULL, 'o-Toluoyl chloride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, 'Benzyl chloride', NULL, '50 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, '(Bromomethyl)cyclohexane', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Sigma Aldrich', NULL, NULL, '4-Hydroxyl-4-methyl-2-pentanone', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '3,5-Dimethylbenzoyl chloride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Alfa aesar', NULL, NULL, '2-Fluoropyridine', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'TCI', NULL, NULL, '9-Bromofluorene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A3', 'Alfa aesar', NULL, NULL, 'Dimethylphenylphosphine', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, 'a-bromo-o-xylene', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '4-Butylbenzyl bromide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '3-Fluorobenzyl Bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '2-phenyl-4,4-5,5-tetramethyl-1,3,2-dioxaborolane', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '2-(trifluoromethyl)benzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '5-Fluoro-2-methylbenzyl bromide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '1-(Bromomethyl)-3-phenoxybenzene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Thermo', NULL, NULL, '2-Fluorobenzyl bromide', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Thermo', NULL, NULL, '3-Methylbenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Thermo', NULL, NULL, '1-Fluoro-2,4-dinitrobenzene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, 'Biphenyl-3-carboxaldehyde', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Alfa aesar', NULL, NULL, '3-(Bromomethyl)benzontirile', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '15-Crown-5 ether', NULL, '5 ml', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, '9,10-Dimethylanthracene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Sigma Aldrich', NULL, NULL, 'Benzoyl chloride', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, 'Benzo(f)quinoline', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Sigma Aldrich', NULL, NULL, 'Bromocyclopentane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'TCI', NULL, NULL, 'Ethyl a-Iodophenylacetate', NULL, '5G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Thermo', NULL, NULL, '2-(Bromomethyl)benzonitrile', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Sigma Aldrich', NULL, NULL, '1,3,5-Trimethoxybenzene', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Sigma Aldrich', NULL, NULL, 'Acetanilide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Sigma Aldrich', NULL, NULL, '(nitromethyl)benzene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'A4', 'Thermo', NULL, NULL, 'Vanadium(3) chloride', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Benzophenone imine', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Chlorobenzene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Thermo', NULL, NULL, '4-(trifuloromethyl)benzoyl chloride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, 'Eicosane', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '1,1-CF3,Br-methylbenzene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '1,3-Diazabicyclo(5.4.0)undec-7-ene(DBU)', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Triethylamine', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Bromocyclohexane', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Phenol', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Vinylmagnesium bromide solution', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Benzonitrile', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Morpholine', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Methanol', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Sodium nitrite', NULL, '500 G', NULL, NULL, 1, NULL),
('box3', 'Under B1', 'Sigma Aldrich', NULL, NULL, 'Methylmagnesium chloride(3.0M THF)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Sodium bis(trimethylsilyl)amide solution(1.0M THF)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'N,N-Dimethylformamide', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Mesitylene', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Aniline', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, '1,4-Dioxane', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Dimethylamine solution(2.0M THF)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', 'Sigma Aldrich', NULL, NULL, 'Benzyl alchol', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C1', NULL, NULL, NULL, 'Triglyne', NULL, '50ml vial', NULL, NULL, 1, NULL),
('box3', 'C1', NULL, NULL, NULL, 'PEHA', NULL, '50ml vial', NULL, NULL, 1, NULL),
('box3', 'C2', 'Sigma Aldrich', NULL, NULL, 'TPPCo', NULL, '500 mg', NULL, NULL, 1, NULL),
('box3', 'C2', 'Thermo', NULL, NULL, 'Aluminum chloride', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'Sigma Aldrich', NULL, NULL, 'Tributyl phosphineoxide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'TCI', NULL, NULL, '9-Bromofluorene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'Thermo', NULL, NULL, 'Potassium nitrite', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'Sigma Aldrich', NULL, NULL, '3-Bromo-1-phenyl-1-propene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'Sigma Aldrich', NULL, NULL, 'Sodium nitrite N15', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'C2', 'Sigma Aldrich', NULL, NULL, 'Tetrabutylammonium nitrite', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'Potassium phosphate tribasic', NULL, '500 G', NULL, NULL, 1, NULL),
('box3', 'DW', 'Sigma Aldrich', NULL, NULL, '1-Iodohexane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Thermo', NULL, NULL, 'Methyl (trifluoromethanesulfonate)', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Tetraethylammonium nitrate', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Iodocyclohexane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Iodocyclohexane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, '[4-(bromomethyl)phenyl]boronic Acide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, '4-Iodobenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, '1-(bromomethyl) napthalene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, '3-(Bromomethyl)-5-chlorobenzo[b]thiophene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Thermo', NULL, NULL, 'Benzophenone oxime', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '2,4,6-trimethylbenzoyl chloride', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, 'Methyl-3-(bromomethyl)benzoate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'TCI', NULL, NULL, '2-Chlorobenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, '3,5-Dimethoxylbenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, 'Nitrosobenzene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Methylithium solution(1.6M ether)', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Thermo', NULL, NULL, 'Benzophenone oxime', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Methylithium solution(1.6M ether)', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Acros', NULL, NULL, '1-(bromoehtyl)benzene', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Pyridine', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Borane tetrahydrofuran complex(1.0M)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'sigma Aldrich', NULL, NULL, 'Iodomethane solution(2.0M tbutyl methyl ether)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, 'Methyl a-bromophenylacetate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Methylithium solution(1.6M ether)', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Alfa', NULL, NULL, 'Acetophenone oxime', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Hydrogen Chloride solution(4.0M dioxane)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'TEMPO', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, 'Dimethyl sulfide', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, '2-Iodopropane', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, '3-Bromo-1-butyne', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Alfa', NULL, NULL, 'tert-Nitrosobutane dimer', NULL, '250 mg', NULL, NULL, 1, NULL),
('box3', 'B2', 'Acros', NULL, NULL, '3-Methoxybenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'tert-butyl isocyanide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, 'Dimethyl sulfoxide', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, 'n-butylithium solution(1.6M hexane)', NULL, '100 ml', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, 'Sodium formate', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, 'Ammonium formate', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, 'N-Chlorosuccinimide', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'C3', 'Thermo', NULL, NULL, 'N,N''-Dimethylethylene diamine', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'C3', 'Sigma Aldrich', NULL, NULL, '12-Crown-4', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'Sigma Aldrich', NULL, NULL, '3-Bromo-1-phenyl-propene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B2', 'Sigma Aldrich', NULL, NULL, 'Tri-tert-Butylphosphine solution(1.0M THF)', NULL, '25 ml', NULL, NULL, 1, NULL),
('box3', 'TOP', 'Sigma Aldrich', NULL, NULL, 'N-Chlorosuccininimide', NULL, '100 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-(methylsulfonyl)benzyl bromide', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Thermo', NULL, NULL, '18-Crown-6', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, 'Methyl-(E)-4-(Bromomethyl)cinnnamate', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-Bromobenzyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-Bromomethylbiphenyl', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-(Bromomethyl)benzophenone', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-Cyanobenzyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Sigma Aldrich', NULL, NULL, '4-(Bromomethyl)benzoic acid', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'sigma Aldrich', NULL, NULL, '2-(Bromomethyl)napthalene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Thermo', NULL, NULL, '4-Nitrobenzyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'sigma Aldrich', NULL, NULL, '4-Methylbenzyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-(trifluoromethyl)benzaldehyde', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, 'Methyl 4-(Bromomethyl)benzoate', NULL, '10 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'TCI', NULL, NULL, '4-(Trifluoromethyl)benzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'B1', 'Acros', NULL, NULL, '4-Chlorobenzyl bromide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'sigma Aldrich', NULL, NULL, 'Benzyl bromide', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Thermo', NULL, NULL, '1-Bromoethylbenzene', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Thermo', NULL, NULL, 'Iodocyclopentane', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'sigma Aldrich', NULL, NULL, 'Iodocyclohexane', NULL, '25 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Acros', NULL, NULL, 'Cobaltocene', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Acros', NULL, NULL, 'Benzoyl bromide', NULL, '5 ml', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Thermo', NULL, NULL, '1,3-cyclohexadiene', NULL, '5 ml', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Thermo', NULL, NULL, 'tert-butylisocyanide', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'Thermo', NULL, NULL, 'Nitrosonium tetrafluoroborate', NULL, '2 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'sigma Aldrich', NULL, NULL, 'Iodobenzene', NULL, '5 G', NULL, NULL, 1, NULL),
('box3', 'Freezer', 'sigma Aldrich', NULL, NULL, '1,2-Bis(dichlorophosphino)ethane', NULL, '1 G', NULL, NULL, 1, NULL),
('box3', 'DF', 'TCI', NULL, NULL, 'a-bromodiphenylmethane', NULL, '25 G', NULL, NULL, 1, NULL),
('box2', 'Freezer-1F', 'Aldrich', '122-52-1', 'T61204', 'Triethyl phosphite', '0.98', '100 mL', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-1F', 'Aldrich', NULL, '324108', 'Trimethylphosphine solution', '1 M in THF', '100 mL', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-1F', 'Aldrich', '116-11-0', '174645', '2-Methoxypropene', '0.97', '50 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-1F', 'TCI', NULL, NULL, 'chlorodiphenyl phosphine', NULL, '25g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', NULL, NULL, NULL, 'benzyl bromide', '0.98', '10ml vial', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '589-57-2', 'D91659', 'Diethylfluorophosphite', '0.95', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '624-73-7', 'D122807', '1,2-Diiodoethane', '0.99', '25 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Alfa', '0274-07-07', 'L14998', 'Catecholborane', '0.97', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Alfa', '25015-63-8', 'L17558', 'Pinacolborane', '0.97', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '591-50-4', NULL, 'Iodobenzene', '0.98', '5g', NULL, NULL, 2.0, NULL),
('box2', 'Freezer-2F-tray', 'Alfa', '27607-77-8', 'A12535', 'Trimethylsilyl trifluoromethanesulfonate', '0.99', '10 g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, '337773', 'Chlorodiisopropylphosphine', '0.96', '5 g', NULL, NULL, 3.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, '260630-1G', 'tert-Butyl isocyanide', '0.98', '1g', NULL, NULL, 2.0, NULL),
('box2', 'Freezer-2F-tray', 'Alfa', NULL, NULL, 'nitrosonium tetrafluoroborate', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '333-27-7', '164283-10G', 'Methyl trifluoromethanesulfonate', '0.98', '10G', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', NULL, NULL, NULL, '2-fluorophyridine', '0.99', '10mL vial', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', NULL, NULL, NULL, 'Phenyl silane', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, 'TEMPO', NULL, '1g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, 'Diethylfluorophosphite', '0.95', '5g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '771-60-8', NULL, '2,3,4,5,6-pentafluoroaniline', '0.99', '5G', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', '773-82-0', NULL, '2,3,4,5,6-pentafluorobenzonitrile', '0.99', '10G', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'tci', NULL, NULL, 'alpha-bromo diphenyl methane', NULL, '10ml vial', NULL, NULL, 1, NULL),
('box2', 'Freezer-2F-tray', NULL, NULL, NULL, '2-fluoro pyridine', '0.99', '10ml vial', NULL, NULL, 1, NULL),
('box2', 'Freezer-2F-tray', 'thermo fischer', NULL, NULL, '1,3-cychlohexadiene', NULL, NULL, NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'aldrich', NULL, NULL, 'phenyl acetylene', NULL, '25ml', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'aldrich', NULL, NULL, '1-azidoadamantane', '0.97', '1g', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'aldrich', NULL, NULL, '4-azidotoluene solution', '0.5M tertbutyl methyl ether', '10ml', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', NULL, NULL, NULL, 'pentafluoro styrene', '0.99', '5ml vial', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, 'benzyl azide solution', '0.5M in DCM', '10ml', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, 'azido benzene', '0.5M tertbutyl methyl ether', '10ml', NULL, NULL, 2.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, '4-azidoanisole solution', '0.5M tertbutyl methyl ether', '10ml', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, '1-azido-4-fluorobenzene solution', '0.5M tertbutyl methyl ether', '10ml', NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Aldrich', NULL, NULL, '1,4 Cyclohexadiene', NULL, NULL, NULL, NULL, 1.0, NULL),
('box2', 'Freezer-2F-tray', 'Ambeed', '11077-24-0', 'A448548', 'Ferrocenium hexafluorophosphate', '0.98', '1g', NULL, NULL, 1.0, NULL),
('box2', NULL, NULL, NULL, NULL, 'benzyl chloride', '0.99', '10ml vial', NULL, NULL, 1, NULL),
('box2', NULL, NULL, NULL, NULL, '1-bromoethyl benzene', '0.97', '10ml vial', NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'Aldrich', '0462-06-06', 'F6001', 'Fluorobenzene', '0.99', '500 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '121-44-8', '471283', 'Triethylamine', '0.995', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '108-86-1', '16350', 'Bromobenzene', '0.995', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '75-77-4', '386529', 'Chlorotrimethylsilane', '0.99', '25 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Acros', '108-90-7', '396971000', 'Chlorobenzene', '0.998', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Alfa', '75-75-2', 'A13565', 'Methane sulfonic acid', '0.98', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', NULL, NULL, NULL, 'Acetone', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'Aldrich', '7778-85-0', '281604', '1,2-Dimethoxypropane', '0.99', '5 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', NULL, NULL, NULL, 'DME with soldium', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', NULL, NULL, NULL, 'Fluorobenzene with molecular sieve', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'TCI', '1069-08-05', 'D3244', 'Dichloro(diethylamino)phosphine', '0.98', '25 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', '1069-08-05', 'D3244', 'Dichloro(diethylamino)phosphine', '0.98', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', NULL, NULL, 'Acyl Chloride', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'Aldrich', NULL, NULL, 'Methyl Iodide solution 2M', '2M', '100mL', NULL, NULL, 2.0, NULL),
('box2', 'Coldwell', 'Aldrich', '1975-03-06 00:00:00', 'I7780-100G', 'Iodoethane', '99% (reagent plus)', '100g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', NULL, NULL, 'benzyl mercaptan', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'TCI', NULL, NULL, 'Silver hexafluorophosphate', '0.98', '5g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', '109-63-7', 'B0527', 'Boron trifluoride diethyl etherate', '>98%', '100ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', '1109-15-5', 'T2313', 'Tris(pentafluorophenyl)borane', '>98%', '1g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '109-72-8', '186171', 'n-butyl lithium solution', '1.6 M in hexane', NULL, NULL, NULL, 2.0, NULL),
('box2', 'Coldwell', 'Aldrich', '7647-01-0', '455189', 'Hydrogen chloride solution', '2 M in diethylether', '100 mL', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '7647-01-0', '345547', 'Hydrogen chloride solution', '4 M in dioxane', '100 mL', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', NULL, NULL, 'chlorodiphenylphosphine', NULL, '100g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', '630-18-2', 'T72001-25G', 'Pivalonitrile', '0.98', '25 mL', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', '1109-15-5', 'T2313', 'Tris(pentafluorophenyl)borane', '>98%', '1g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '75-77-4', '386529', 'Chlorotrimethylsilane', '0.99', '25 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Acros', '108-90-7', '396971000', 'Chlorobenzene', '0.998', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', NULL, NULL, NULL, 'Fluorobenzene with molecular sieve', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'Alfa', '75-75-2', 'A13565', 'Methane sulfonic acid', '0.98', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '0462-06-06', 'F6001', 'Fluorobenzene', '0.99', '500 g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'Aldrich', '108-86-1', '16350', 'Bromobenzene', '0.995', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', 'TCI', NULL, NULL, 'Silver hexafluorophosphate', '0.98', '5g', NULL, NULL, 1.0, NULL),
('box2', 'Coldwell', NULL, NULL, NULL, 'Acetone', NULL, 'vial', NULL, NULL, 1, NULL),
('box2', 'Coldwell', 'Aldrich', NULL, NULL, 'chlorodiphenylphosphine', NULL, '100g', NULL, NULL, 1.0, NULL),
('box2', 'Left corner', 'Aldrich', '100-58-3', '331376', 'Phenylmagnesiumbromide solution', '1.0 M in THF', '800 ml', NULL, NULL, 2.0, NULL),
('box2', 'Left corner', 'Aldrich', '110-82-7', '227048', 'Cyclohexane', '0.995', '1 L', NULL, NULL, 1.0, NULL),
('box2', 'Left corner', 'Aldrich', '109-72-8', '186171', 'n-Butylithium solution', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'Left corner', 'Aldrich', '123-91-1', '296309', '1,4-dioxane', '0.998', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '112-60-7', '110175', 'Tetraethylene glycol', '0.99', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '98-80-6', 'P20009', 'Phenylboronic acid', '0.95', '10 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Alfa', '2923-28-6', '88722', 'Silver trifluoromethanesulfonate', '0.98', '2 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '24388-23-6', '647098', 'Phenylboronic acid pinacol ester', '0.97', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '13826-27-2', '473286', 'Bis(catecholato)diboron', '0.97', '1 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '104-66-5', '140287', '1,2-diphenoxyethane', '0.99', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', '33100-27-5', '18832', '15-crown-5', '0.98', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', NULL, NULL, NULL, '18-crown-6', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T1', NULL, NULL, NULL, 'Diphenylether', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T1', 'TCI', '3558-60-9', 'P1263', '2-Phenylethyl Methyl Ether', '0.98', '25mL', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'TCI', '100-47-0', 'B0082', 'Benzonitrile', '0.99', '25 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', NULL, '194905', '12-Crown-4', '0.98', '1 g, small amount', NULL, NULL, 2.0, NULL),
('box2', 'T1', 'Aldrich', '6192-52-5', '402885', 'p-Toluenesulfonic acid monohydrate', '0.985', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'TCI', NULL, 'C0892', 'Cyclohexyltrichlorosilane', NULL, '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Alfa', '140681-55-6', 'L17003', '1-Chloromethyl-4-fluoro-1,4-diazoniabicyclo[2.2.2]octane bis(tetrafluoroborate)', '0.98', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'TCI', '934-87-2', 'T0849', 'S-Phenyl thioacetate', '0.98', '25mL', NULL, NULL, 1.0, NULL),
('box2', 'T1', 'Aldrich', NULL, '241989', 'Ethoxybenzene', '0.99', '100mL', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'Aldrich', '603-35-0', '93090', 'Triphenylphosphine', '0.985', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'TCI', '110-71-4', 'D0634', '1,2-Dimethoxyethane', '0.99', '500 mL', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'Aldrich', '109-72-8', '186171', 'n-Butylithium solution', '1.6 M in hexane', '100 mL', NULL, NULL, 2.0, NULL),
('box2', 'T2', 'Aldrich', '1068-55-9', '230111', 'Isopropylmagnesium chloride', '2.0 M in THF', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'Aldrich', '16853-85-3', '212776', 'Lithium aluminium hydride solution', '1.0 M in THF', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'Acros', '180675-22-3', '438861000', '(1,3-dioxalan-2-ylmethyl)magnesium bromide', '0.5 M in THF', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'T2', 'TCI', '13826-27-2', 'B3757', 'Bis(catecholato)diboron', '0.98', '1g', NULL, NULL, 1.0, NULL),
('box2', 'M1', NULL, NULL, NULL, 'Nickel(II) chloride', '0.98', NULL, NULL, NULL, 2.0, NULL),
('box2', 'M1', NULL, NULL, NULL, 'Cobalt(II) bromide', '0.99', NULL, NULL, NULL, 1.0, NULL),
('box2', 'M1', NULL, NULL, NULL, 'Nickelocene', NULL, NULL, NULL, NULL, 1.0, NULL),
('box2', 'M1', NULL, NULL, NULL, 'Lithium aluminium hydride', NULL, NULL, NULL, NULL, 1.0, NULL),
('box2', 'M1', NULL, NULL, NULL, 'Magnesium', NULL, NULL, NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Aldrich', '28923-39-9', '406341', 'Nickel(II) bromide ehtylene glycol dimethylether complex', '0.97', '5 g', NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Aldrich', '7440-31-5', '243434', 'Tin', '0.995', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Acros', NULL, NULL, 'Molybdenum(V) chloride', '0.95', '10 g', NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Aldrich', NULL, '400777', 'Nickel Iodide', '95% >', NULL, NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Aldrich', '7446-70-6', '206911', 'Aluminium chloride', '0.98', '100 g', NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Alfa Aesar', '144026-79-9', 'MFCD00798539', 'Scandium (III) trisfluoromethanesulfonate', '0.98', '1g', NULL, NULL, 1.0, NULL),
('box2', 'M1', 'Sigma Aldrich', '52093-30-8', '425745', 'Yttrium(III) trisfluoromethanesulfonate', '0.98', '5g', NULL, NULL, 1.0, NULL),
('box2', NULL, NULL, NULL, NULL, 'Mg powder', NULL, NULL, NULL, NULL, 1, NULL),
('box2', NULL, NULL, NULL, NULL, 'Zinc powder', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T2', 'Aldrich', '180675-22-3', '438861000', '(1,3-dioxalan-2-ylmethyl)magnesium bromide', '0.5 M in THF', '100 ml', NULL, NULL, 2.0, NULL),
('box2', 'T3', NULL, NULL, NULL, 'trimethoxybenzene', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, 'mesitylene', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', 'TCI', '882-33-7', 'P0167', 'Diphenyl Disulfide', '0.99', '25g', NULL, NULL, 1.0, NULL),
('box2', 'T3', 'TCI', '150-60-7', 'B0417', 'Dibenzyl Disulfide', '0.98', '25g', NULL, NULL, 1.0, NULL),
('box2', 'T3', NULL, NULL, NULL, 'Sodium thiomethoxide', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, 'Graphite', NULL, '28g', NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, 'B2Pin2 bis(pinacolato)boron', '0.98', '2g', NULL, NULL, 1, NULL),
('box2', 'T3', 'Aldrich', '100-32-3', 'N21022', '4-Nitrophenyl disulfide', '> 95%', '25g', NULL, NULL, 1.0, NULL),
('box2', 'T3', NULL, NULL, NULL, 'Sodium Hydride', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, 'Sodium Oxalate', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, '9,10-dihydroanthracene', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, 'TMEDA (tetramethylethylenediamine)', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', NULL, NULL, NULL, '1,4-benzoquinone', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', 'Aldrich', '97-00-7', '237329', '1-chloro-2,4-dinitrobenzene', '>99%', '10g', NULL, NULL, 1.0, NULL),
('box2', 'T3', 'Aldrich', '108-98-5', '240249', 'Thiophenol', '>99%', '10g', NULL, NULL, 1.0, NULL),
('box2', 'T3', NULL, NULL, NULL, 'Biphenyl', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T3', 'Thermo', NULL, NULL, 'NaOH', NULL, NULL, NULL, NULL, 1, NULL),
('box2', 'T4', 'Aldrich', NULL, NULL, 'n-Butylithium solution', '1.6 M in hexane', '100 mL', NULL, NULL, 2.0, NULL),
('box2', 'T4', 'Aldrich', NULL, NULL, 'NaHMDS solution', '1 M in THF', '100 mL', NULL, NULL, 1.0, NULL),
('box2', 'T4', 'Aldrich', '676-58-4', '189901-100ML', 'Methylmagnesium chloride', '3 M in THF', '100 mL', NULL, NULL, 2.0, NULL),
('box2', 'T4', 'Aldrich', NULL, NULL, '4-fluorophenyl Magnesium bromide solution', '1.0 M in THF', '100 ml', NULL, NULL, 1.0, NULL),
('box2', 'T4', 'Aldrich', '22560-16-3', NULL, 'Lithium triethyl borohydride solution (Super Hydride solution)', '1.0 M in THF', '25 ml', NULL, NULL, 1.0, NULL),
('box2', NULL, NULL, NULL, NULL, 'Cyclohexene', NULL, NULL, NULL, NULL, 1, NULL);
